#写一个底部的config，带有title：Hello! This is how_to_create email:fairzlq@gmail.com
title: Hello! This is how_to_create
email: fairzlq@gmail.com
description: >- 
  Githubtohaoyangli own page. 
  Githubtohaoyangli的个人页面
url: "githubtohaoyangli.github.io"
icon: "/favicon.ico"
github_username:  githubtohaoyangli
theme: minima
plugins:
  - jekyll-feed
